In [ ]:
!git clone https://github.com/otman-ai/mediasearch.git

Cloning into 'mediasearch'...
remote: Enumerating objects: 131, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 131 (delta 52), reused 100 (delta 31), pack-reused 0 (from 0)
Receiving objects: 100% (131/131), 6.38 MiB | 12.49 MiB/s, done.
Resolving deltas: 100% (52/52), done.

In [ ]:
%cd /content/mediasearch
!pip install -e . -q

/content/mediasearch
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 5.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 101.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 MB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.9/887.9 MB 560.5 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 67.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 706.8/706.8 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.4/322.4 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 MB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 67.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 4.2 MB/s eta 0:00:00
  Building editable for mediasearch (pyproject.toml) ... done
  Building wheel for clip (setup.py) ... done
  Building wheel for openai-whisper (pyproject.toml) ... done

In [ ]:
!hf download friedrichor/MSR-VTT \
    --repo-type dataset \
    --local-dir ./MSR-VTT

Downloading bytes:           |  0.00B
Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 12 files:   0% 0/12 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0% 0.00/14.2M [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/37.3M [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/48.4M [00:00<?, ?B/s]Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Reconstructing (incomplete total...):   0% 0.00/2.24G [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/2.24G [00:00<?, ?B/s]
Downloading bytes:   0% 74.5k/2.24G [00:00<1:05:04, 573kB/s]

Fetching 12 files:   8% 1/12 [00:00<00:01,  7.55it/s]
Reconstructing (incomplete total...):   0% 74.5k/2.24G [00:00<1:04:50, 575kB/s]
Reconstructing (incomplete total...):   0% 75.8k/2.24G [00:00<1:04:50, 575kB/s]
Reconstructing (incomplete total...):   0% 78.4k/2.24G [00:00<1:04:51, 575kB/s]
Downloading bytes:   0% 420k/2.24G [00:00<19:52, 1.88MB/s]

Fetching 12 files:  33% 4/12 [00:00<00:00, 17.33it/s]
Reconstructing (incomplete total...):   0% 420k/2.26G [00:00<20:05, 1.88MB/s]
Reconstructing (incomplete total...):   0% 420k/2.26G [00:00<20:05, 1.88MB/s]
Reconstructing (incomplete total...):   0% 489k/2.26G [00:00<20:05, 1.88MB/s]
Downloading bytes:   0% 2.14M/2.26G [00:00<13:22, 2.82MB/s, 2.82MB/s  ]
Downloading bytes:   0% 5.12M/2.26G [00:00<06:04, 6.20MB/s, 2.82MB/s  ]

Downloading bytes:   1% 19.9M/2.26G [00:01<01:24, 26.4MB/s, 6.20MB/s  ]
Reconstructing (incomplete total...):   3% 75.1M/2.26G [00:01<00:22, 95.3MB/s, 14.8MB/s  ]

Downloading bytes:  10% 216M/2.26G [00:01<00:08, 255MB/s,  253MB/s  ]
Downloading bytes:  33% 744M/2.26G [00:02<00:03, 469MB/s,  447MB/s  ]
Downloading bytes:  36% 819M/2.26G [00:02<00:03, 429MB/s,  469MB/s  ]
Downloading bytes:  83% 1.89G/2.26G [00:05<00:01, 356MB/s,  394MB/s  ]
Downloading bytes:  98% 2.22G/2.26G [00:06<00:00, 292MB/s,  313MB/s  ]
Reconstructing (incomplete total...):  68% 1.55G/2.26G [00:08<00:03, 204MB/s,  117MB/s  ]
Fetching 12 files: 100% 12/12 [00:15<00:00,  1.32s/it]
Download complete: 100% 2.22G/2.22G [00:15<00:00, 292MB/s,  292MB/s  ]
Reconstruction complete: 100% 2.26G/2.26G [00:15<00:00, 138MB/s,  138MB/s  ]             ✓ Downloaded
  path: /content/mediasearch/MSR-VTT
Download complete: 100% 2.22G/2.22G [00:15<00:00, 140MB/s,  292MB/s  ]
Reconstruction complete: 100% 2.26G/2.26G [00:15<00:00, 142MB/s,  138MB/s  ]

In [ ]:
!unzip  /content/mediasearch/MSR-VTT/MSRVTT_Videos.zip -d /content/mediasearch/MSR-VTT/MSRVTT_Videos

Streaming output truncated to the last 5000 lines.
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4932.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4052.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9405.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9662.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6804.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3502.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video914.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1178.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2581.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3564.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7478.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1998.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4501.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7767.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5344.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9667.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5641.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3020.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8264.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8271.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2395.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9520.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4770.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3111.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7591.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3306.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2534.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9247.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8966.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5083.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3644.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3376.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4773.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7722.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3771.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1129.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5758.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3227.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8991.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7885.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2692.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3392.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3947.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9351.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6859.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7642.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7073.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1208.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2735.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5342.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8398.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5969.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9456.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2812.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9240.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5846.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6182.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7589.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8933.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2574.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3495.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video698.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1215.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2308.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8353.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9339.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4004.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7686.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7090.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5970.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2622.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7689.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6656.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8279.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7694.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5332.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7996.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7716.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9808.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7764.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8252.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9649.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2208.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3119.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8524.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3481.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8193.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1049.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7191.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3244.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1374.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6957.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7626.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1281.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7463.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1663.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2131.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3049.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1423.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4507.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8235.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4248.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5229.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2099.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video862.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1026.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1811.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4325.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5202.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1079.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2754.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9958.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8096.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7001.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2150.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1008.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3230.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6396.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3541.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1949.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6651.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4697.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4886.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6406.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3339.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2851.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7779.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3043.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5102.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6951.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1466.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8014.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3660.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1259.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7778.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5268.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5617.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4458.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7786.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3103.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9657.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7856.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3366.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1286.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2148.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3686.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8075.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8750.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5899.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6831.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video34.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6504.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9980.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9641.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4581.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8346.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1383.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7740.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7576.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5678.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4203.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8874.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4285.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2611.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4839.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video60.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1081.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5965.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5319.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9175.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7489.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video11.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8401.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video727.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8733.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6521.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6186.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4741.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6084.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9604.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6201.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5232.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2136.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4284.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8306.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4042.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1735.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8481.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3055.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9320.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3861.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7013.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8089.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1645.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3617.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1699.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9294.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6116.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8675.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8284.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2467.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5239.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4212.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3856.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1133.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3264.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5065.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5632.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5629.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6699.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3305.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1496.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2848.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7993.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8234.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9035.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1030.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1677.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2537.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1450.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2460.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5845.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1212.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2295.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8434.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3821.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6838.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1422.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8591.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9258.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2219.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3108.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1068.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6761.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6479.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3011.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video495.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7775.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video741.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video2713.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8582.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3598.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4145.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4774.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6653.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9540.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1668.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7497.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6345.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6072.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5389.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7452.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video1757.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video685.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9700.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video3910.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5063.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video5626.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6051.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9898.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video4365.mp4
  inflating: /content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video6639.mp4

## Evaluate on the `Test` dataset

In [ ]:
import pandas as pd
import json
test_dataset_path = "/content/mediasearch/MSR-VTT/msrvtt_test_1k.json"

test_dataset = pd.read_json(test_dataset_path)
test_dataset.head()

,video_id,video,caption,source,category,url,start time,end time,id
0,video7020,video7020.mp4,a woman creating a fondant baby and flower,MSR-VTT,10,https://www.youtube.com/watch?v=4KRMJNBjrEs,221.77,233.08,7020
1,video7021,video7021.mp4,baseball player hits ball,MSR-VTT,3,https://www.youtube.com/watch?v=bsTJrmwyr-k,20.38,31.96,7021
2,video7024,video7024.mp4,little pet shop cat getting a bath and washed ...,MSR-VTT,13,https://www.youtube.com/watch?v=VjbTyUPaNtY,78.83,95.24,7024
3,video7025,video7025.mp4,a naked child runs through a field,MSR-VTT,7,https://www.youtube.com/watch?v=-iEnLnezuxE,1442.41,1456.84,7025
4,video7026,video7026.mp4,a man is giving a review on a vehicle,MSR-VTT,9,https://www.youtube.com/watch?v=GQ_0nK6-vNg,284.73,298.35,7026

In [ ]:
test_dataset["video_path"] = test_dataset["video_id"].apply(lambda x: f"/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/{x}.mp4")
test_dataset.head()

,video_id,video,caption,source,category,url,start time,end time,id,video_path
0,video7020,video7020.mp4,a woman creating a fondant baby and flower,MSR-VTT,10,https://www.youtube.com/watch?v=4KRMJNBjrEs,221.77,233.08,7020,/content/mediasearch/MSR-VTT/MSRVTT_Videos/vid...
1,video7021,video7021.mp4,baseball player hits ball,MSR-VTT,3,https://www.youtube.com/watch?v=bsTJrmwyr-k,20.38,31.96,7021,/content/mediasearch/MSR-VTT/MSRVTT_Videos/vid...
2,video7024,video7024.mp4,little pet shop cat getting a bath and washed ...,MSR-VTT,13,https://www.youtube.com/watch?v=VjbTyUPaNtY,78.83,95.24,7024,/content/mediasearch/MSR-VTT/MSRVTT_Videos/vid...
3,video7025,video7025.mp4,a naked child runs through a field,MSR-VTT,7,https://www.youtube.com/watch?v=-iEnLnezuxE,1442.41,1456.84,7025,/content/mediasearch/MSR-VTT/MSRVTT_Videos/vid...
4,video7026,video7026.mp4,a man is giving a review on a vehicle,MSR-VTT,9,https://www.youtube.com/watch?v=GQ_0nK6-vNg,284.73,298.35,7026,/content/mediasearch/MSR-VTT/MSRVTT_Videos/vid...

In [ ]:

from mediasearch.vit import VideoQuery
config = {
        "model_name": "ViT-B/32",
        "frame_rate": 3,
        "threshold": 0.25,
        "debug": False
}

video_search = VideoQuery(**config)
print(video_search.cash)

In [ ]:
%%time
video_search.insert_videos(videos_path=list(test_dataset["video_path"]))

In [ ]:
video_search.device

'cuda'

In [ ]:

from mediasearch.vit import VideoQuery
config = {
        "model_name": "ViT-B/32",
        "frame_rate": 3,
        "threshold": 0.25,
        "debug": False,
        "cash":"/content/drive/MyDrive/mediasearch/embeddings.h5"
}
video_search = VideoQuery(**config)

In [ ]:
video_search.search("baseball player hits ball")

{'/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7021.mp4': [(0.0,
   1.0,
   0.32680606842041016),
  (1.0, 2.0, 0.3353806138038635),
  (2.0, 3.0, 0.32924407720565796),
  (11.0, 12.0, 0.3219556510448456)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7556.mp4': [(0.0,
   1.0,
   0.31914010643959045),
  (1.0, 2.0, 0.3132617175579071),
  (5.0, 6.0, 0.3182341456413269)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video7787.mp4': [(0.0,
   1.0,
   0.3206508755683899)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8013.mp4': [(6.0,
   7.0,
   0.31818026304244995)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8049.mp4': [(0.0,
   1.0,
   0.3224745988845825),
  (3.0, 4.0, 0.31969767808914185),
  (4.0, 5.0, 0.31563717126846313),
  (10.0, 11.0, 0.3157986104488373),
  (11.0, 12.0, 0.3386780321598053),
  (12.0, 12.666666666666666, 0.3194248080253601)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8079.mp4': [(2.0,
   3.0,
   0.3112996220588684),
  (5.0, 6.0, 0.3233826160430908)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8308.mp4': [(0.0,
   1.0,
   0.340739905834198),
  (3.0, 4.0, 0.3213074207305908),
  (5.0, 6.0, 0.32619065046310425)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8913.mp4': [(3.0,
   4.0,
   0.324252188205719)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9021.mp4': [(0.0,
   1.0,
   0.3388167917728424)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9534.mp4': [(8.0,
   9.0,
   0.3232373297214508),
  (10.0, 11.0, 0.32014137506484985),
  (11.0, 12.0, 0.3167935609817505),
  (15.0, 16.0, 0.32003581523895264)],
 '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video9823.mp4': [(6.0,
   7.0,
   0.3120042085647583),
  (9.0, 10.0, 0.31930387020111084),
  (26.0, 27.0, 0.32114875316619873)]}

In [ ]:
import os
from IPython.display import Video


video_file = '/content/mediasearch/MSR-VTT/MSRVTT_Videos/video/video8049.mp4'
Video(video_file, embed=True)

In [ ]:
test_dataset.shape

(1000, 10)

In [ ]:

from tqdm import tqdm
score = 0
for row in tqdm(test_dataset.iterrows()):
  query = row[1]["caption"]
  video_path = row[1]["video_path"]
  results = video_search.search(query) # then you can query
  if video_path in results.keys():
    score +=1
print(f"Out if the {test_dataset.shape[0]} videos, {score} videos matched correctly")

93it [02:23,  1.50s/it]

In [ ]:
import os
from IPython.display import Video


video_file = '/content/MSR-VTT/MSRVTT_Videos/video/video5.mp4'
Video(video_file, embed=True)

## Deployments

In [2]:
!hf download friedrichor/MSR-VTT \
    --repo-type dataset \
    --local-dir ./MSR-VTT

Hint: A new version of huggingface_hub (1.30.0) is available! You are using version 1.28.0.
To update, run: hf update
Hint: The `hf-cli` skill is not installed. Run `hf skills add -g --claude` to teach your AI agents how to use the `hf` CLI.
Downloading bytes:           |  0.00B
Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 12 files:   0% 0/12 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0% 0.00/48.4M [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/48.4M [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/48.4M [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/2.24G [00:00<?, ?B/s]Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Reconstructing (incomplete total...):   0% 0.00/2.24G [00:00<?, ?B/s]
Downloading bytes:   0% 342k/2.24G [00:00<13:42, 2.72MB/s]

Fetching 12 files:   8% 1/12 [00:00<00:01,  7.89it/s]
Reconstructing (incomplete total...):   0% 342k/2.24G [00:00<13:39, 2.73MB/s]
Reconstructing (incomplete total...):   0% 416k/2.24G [00:00<13:39, 2.73MB/s]
Reconstructing (incomplete total...):   0% 418k/2.24G [00:00<13:39, 2.73MB/s]

Fetching 12 files:  33% 4/12 [00:00<00:00, 19.53it/s]
Reconstructing (incomplete total...):   0% 420k/2.26G [00:00<13:48, 2.73MB/s]
Reconstructing (incomplete total...):   0% 420k/2.26G [00:00<13:48, 2.73MB/s]
Reconstructing (incomplete total...):   0% 489k/2.26G [00:00<13:48, 2.73MB/s]
Reconstructing (incomplete total...):   0% 578k/2.26G [00:00<13:48, 2.73MB/s]

Fetching 12 files:  58% 7/12 [00:00<00:00, 23.29it/s]
Downloading bytes:   0% 9.45M/2.26G [00:01<03:51, 9.74MB/s, 5.89MB/s  ]
Reconstructing (incomplete total...):   2% 37.9M/2.26G [00:01<00:53, 41.4MB/s, 15.1MB/s  ]

Downloading bytes:   1% 22.9M/2.26G [00:01<01:18, 28.4MB/s, 9.74MB/s  ]
Downloading bytes:  12% 272M/2.26G [00:01<00:05, 355MB/s,  324MB/s  ]
Downloading bytes:  15% 343M/2.26G [00:02<00:06, 291MB/s,  355MB/s  ]
Downloading bytes:  18% 401M/2.26G [00:02<00:05, 345MB/s,  291MB/s  ]
Downloading bytes:  28% 640M/2.26G [00:02<00:03, 522MB/s,  477MB/s  ]
Downloading bytes:  31% 710M/2.26G [00:02<00:03, 445MB/s,  522MB/s  ]
Downloading bytes:  82% 1.85G/2.26G [00:05<00:00, 470MB/s,  472MB/s  ]
Downloading bytes:  98% 2.22G/2.26G [00:06<00:00, 259MB/s,  297MB/s  ]
Reconstructing (incomplete total...):  68% 1.55G/2.26G [00:09<00:04, 171MB/s,  106MB/s  ]
Reconstructing (incomplete total...): 100% 2.26G/2.26G [00:13<00:00, 174MB/s,  171MB/s  ]

Fetching 12 files: 100% 12/12 [00:13<00:00,  1.16s/it]
Download complete: 100% 2.22G/2.22G [00:13<00:00, 259MB/s,  259MB/s  ]
Reconstruction complete: 100% 2.26G/2.26G [00:13<00:00, 174MB/s,  174MB/s  ]             ✓ Downloaded
  path: /content/MSR-VTT
Download complete: 100% 2.22G/2.22G [00:13<00:00, 160MB/s,  259MB/s  ]
Reconstruction complete: 100% 2.26G/2.26G [00:13<00:00, 163MB/s,  174MB/s  ]

In [7]:
!unzip  /content/MSR-VTT/MSRVTT_Videos.zip -d /content/MSR-VTT/MSRVTT_Videos

Streaming output truncated to the last 5000 lines.
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4932.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4052.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9405.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9662.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6804.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3502.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video914.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1178.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2581.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3564.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7478.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1998.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4501.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7767.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5344.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9667.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5641.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3020.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8264.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8271.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2395.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9520.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4770.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3111.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7591.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3306.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2534.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9247.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8966.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5083.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3644.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3376.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4773.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7722.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3771.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1129.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5758.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3227.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8991.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7885.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2692.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3392.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3947.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9351.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6859.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7642.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7073.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1208.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2735.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5342.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8398.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5969.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9456.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2812.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9240.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5846.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6182.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7589.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8933.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2574.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3495.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video698.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1215.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2308.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8353.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9339.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4004.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7686.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7090.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5970.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2622.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7689.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6656.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8279.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7694.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5332.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7996.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7716.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9808.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7764.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8252.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9649.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2208.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3119.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8524.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3481.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8193.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1049.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7191.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3244.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1374.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6957.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7626.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1281.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7463.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1663.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2131.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3049.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1423.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4507.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8235.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4248.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5229.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2099.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video862.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1026.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1811.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4325.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5202.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1079.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2754.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9958.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8096.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7001.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2150.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1008.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3230.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6396.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3541.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1949.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6651.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4697.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4886.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6406.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3339.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2851.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7779.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3043.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5102.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6951.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1466.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8014.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3660.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1259.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7778.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5268.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5617.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4458.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7786.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3103.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9657.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7856.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3366.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1286.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2148.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3686.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8075.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8750.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5899.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6831.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video34.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6504.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9980.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9641.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4581.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8346.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1383.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7740.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7576.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5678.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4203.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8874.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4285.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2611.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4839.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video60.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1081.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5965.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5319.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9175.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7489.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video11.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8401.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video727.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8733.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6521.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6186.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4741.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6084.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9604.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6201.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5232.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2136.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4284.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8306.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4042.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1735.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8481.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3055.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9320.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3861.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7013.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1645.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3617.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1699.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9294.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6116.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8284.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2467.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5239.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4212.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3856.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1133.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3264.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5065.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5632.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5629.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6699.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3305.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1496.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2848.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7993.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8234.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9035.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1030.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1677.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2537.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1450.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2460.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5845.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1212.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2295.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8434.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3821.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6838.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1422.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8591.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9258.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2219.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3108.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1068.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6761.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6479.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3011.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video495.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7775.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video741.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2713.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8582.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3598.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4145.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4774.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6653.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9540.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1668.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7497.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6345.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6072.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5389.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7452.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1757.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video685.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9700.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3910.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5063.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5626.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6051.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9898.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4365.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6639.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1214.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4878.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video421.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video153.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6013.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3364.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5169.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4964.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2689.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2500.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video931.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7557.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6417.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7208.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2794.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1268.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9853.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video9209.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3704.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8031.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6591.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7481.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2012.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3406.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4198.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video792.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4599.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3575.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2938.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video719.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1194.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6944.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video2648.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7580.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4053.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video7163.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5743.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video1410.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3415.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5693.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3844.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video4159.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video203.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video6214.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video3312.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video866.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8484.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video8516.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video397.mp4
  inflating: /content/MSR-VTT/MSRVTT_Videos/video/video5912.mp4

In [ ]:
import h5py

embeddings_file = "/content/drive/MyDrive/mediasearch/embeddings.h5"
assets_path = "/content/mediasearch/"

with h5py.File(embeddings_file, "r+") as f:

    for key in f.keys():
        # Read the current video path
        video = f[key]["video"][0].decode("utf-8")

        # Replace relative path with absolute path
        new_video = video.replace("/content/mediasearch/", "/content/")

        # Update the dataset
        f[key]["video"][0] = new_video.encode("utf-8")

        print(f"  {video} -> {new_video}")

In [4]:
!git clone https://github.com/otman-ai/mediasearch-api
%cd mediasearch-api
!pip install -r requirements.txt

Cloning into 'mediasearch-api'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 31 (delta 9), reused 31 (delta 9), pack-reused 0 (from 0)
Receiving objects: 100% (31/31), 14.56 KiB | 14.56 MiB/s, done.
Resolving deltas: 100% (9/9), done.
/content/mediasearch-api
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirments.txt'

In [5]:
!pip install -r requirements.txt

  Attempting uninstall: flask
    Found existing installation: Flask 3.1.3
    Uninstalling Flask-3.1.3:
      Successfully uninstalled Flask-3.1.3
  Attempting uninstall: torch
    Found existing installation: torch 2.11.0+cu128
    Uninstalling torch-2.11.0+cu128:
      Successfully uninstalled torch-2.11.0+cu128
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.26.0+cu128
    Uninstalling torchvision-0.26.0+cu128:
      Successfully uninstalled torchvision-0.26.0+cu128
Successfully installed clip-1.0 ffmpeg-python-0.2.0 flask-3.0.3 ftfy-6.3.1 gunicorn-22.0.0 mediasearch-0.1.0 numpy-2.2.6 nvidia-cudnn-cu12-9.10.2.21 nvidia-nccl-cu12-2.27.3 openai-whisper-20250625 opencv-python-4.12.0.88 torch-2.8.0 torchvision-0.23.0 tqdm-4.67.1 triton-3.4.0 ultralytics-8.3.204 ultralytics-thop-2.1.6

In [ ]:
!curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
  | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
  && echo "deb https://ngrok-agent.s3.amazonaws.com bookworm main" \
  | sudo tee /etc/apt/sources.list.d/ngrok.list \
  && sudo apt update \
  && sudo apt install ngrok

In [ ]:
!ngrok config add-authtoken <TOKEN_HERE>

In [5]:
import shutil
import os
os.makedirs("/content/mediasearch-api/data/", exist_ok=True)
shutil.copy("/content/drive/MyDrive/mediasearch/embeddings.h5", "/content/mediasearch-api/data/")

'/content/mediasearch-api/data/embeddings.h5'

In [ ]:
%cd mediasearch-api

In [16]:
!pip install git+https://github.com/otman-ai/mediasearch.git@main

Collecting git+https://github.com/otman-ai/mediasearch.git@main
  Cloning https://github.com/otman-ai/mediasearch.git (to revision main) to /tmp/pip-req-build-8z7cuqrs
  Running command git clone --filter=blob:none --quiet https://github.com/otman-ai/mediasearch.git /tmp/pip-req-build-8z7cuqrs
  Resolved https://github.com/otman-ai/mediasearch.git to commit e2fc2d39656a3d8e3b0c80b51c71002b3be462e0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting clip@ git+https://github.com/openai/CLIP.git@dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1 (from mediasearch==0.1.0)
  Using cached clip-1.0-py3-none-any.whl
Collecting openai-whisper@ git+https://github.com/openai/whisper.git@c0d2f624c09dc18e709e37c2ad90c039a4eb72a2 (from mediasearch==0.1.0)
  Using cached openai_whisper-20250625-py3-none-any.whl
Requirement already satisfied: torch==2.8.0 in /usr/local/lib/python3.13/dist-packages (from mediasearch==0.1.0) (2.8.0)
Requirement already satisfied: opencv-python==4.12.0.88 in /usr/local/lib/python3.13/dist-packages (from mediasearch==0.1.0) (4.12.0.88)
Requirement already satisfied: numpy==2.2.6 in /usr/local/lib/python3.13/dist-packages (from mediasearch==0.1.0) (2.2.6)
Requirement already satisfied: pillow==11.3.0 in /usr/local/lib/python3.13/dist-packages (from mediasearch==0.1.0) (11.3.0)
Requirement already satisfied: ffmpeg-python==0.2.0 in /usr/local/lib/python3.13/dist-packages (from mediasearch==0.1.0) (0.2.0)
Requirement already satisfied: tqdm==4.67.1 in /usr/local/lib/python3.13/dist-packages (from mediasearch==0.1.0) (4.67.1)
Requirement already satisfied: ultralytics==8.3.204 in /usr/local/lib/python3.13/dist-packages (from mediasearch==0.1.0) (8.3.204)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from mediasearch==0.1.0) (3.16.0)
Requirement already satisfied: future in /usr/local/lib/python3.13/dist-packages (from ffmpeg-python==0.2.0->mediasearch==0.1.0) (1.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (3.32.4)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (4.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.13/dist-packages (from torch==2.8.0->mediasearch==0.1.0) (3.4.0)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics==8.3.204->mediasearch==0.1.0) (3.10.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.13/dist-packages (from ultralytics==8.3.204->mediasearch==0.1.0) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics==8.3.204->mediasearch==0.1.0) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from ultralytics==8.3.204->mediasearch==0.1.0) (1.16.3)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics==8.3.204->mediasearch==0.1.0) (0.23.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from ultralytics==8.3.204->mediasearch==0.1.0) (5.9.5)
Requirement already satisfied: polars in /usr/local/lib/python3.13/dist-packages (from ultralytics==8.3.204->mediasearch==0.1.0) (1.35.2)
Requirement already satisfied: ultralytics-thop>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from ultralytics==8.3.204->mediasearch==0.1.0) (2.1.6)
Requirement already satisfied: ftfy in /usr/local/lib/python3.13/dist-packages (from clip@ git+https://github.com/openai/CLIP.git@dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1->mediasearch==0.1.0) (6.3.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from clip@ git+https://github.com/openai/CLIP.git@dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1->mediasearch==0.1.0) (26.3)
Requirement already satisfied: regex in /usr/local/lib/python3.13/dist-packages (from clip@ git+https://github.com/openai/CLIP.git@dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1->mediasearch==0.1.0) (2025.11.3)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.13/dist-packages (from openai-whisper@ git+https://github.com/openai/whisper.git@c0d2f624c09dc18e709e37c2ad90c039a4eb72a2->mediasearch==0.1.0) (10.8.0)
Requirement already satisfied: numba in /usr/local/lib/python3.13/dist-packages (from openai-whisper@ git+https://github.com/openai/whisper.git@c0d2f624c09dc18e709e37c2ad90c039a4eb72a2->mediasearch==0.1.0) (0.61.2)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.13/dist-packages (from openai-whisper@ git+https://github.com/openai/whisper.git@c0d2f624c09dc18e709e37c2ad90c039a4eb72a2->mediasearch==0.1.0) (0.14.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics==8.3.204->mediasearch==0.1.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics==8.3.204->mediasearch==0.1.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics==8.3.204->mediasearch==0.1.0) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics==8.3.204->mediasearch==0.1.0) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics==8.3.204->mediasearch==0.1.0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.3.0->ultralytics==8.3.204->mediasearch==0.1.0) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics==8.3.204->mediasearch==0.1.0) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics==8.3.204->mediasearch==0.1.0) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics==8.3.204->mediasearch==0.1.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.23.0->ultralytics==8.3.204->mediasearch==0.1.0) (2026.7.22)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch==2.8.0->mediasearch==0.1.0) (1.3.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.13/dist-packages (from ftfy->clip@ git+https://github.com/openai/CLIP.git@dcba3cb2e2827b402d2701e7e1c7d9fed8a20ef1->mediasearch==0.1.0) (0.8.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch==2.8.0->mediasearch==0.1.0) (3.0.3)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba->openai-whisper@ git+https://github.com/openai/whisper.git@c0d2f624c09dc18e709e37c2ad90c039a4eb72a2->mediasearch==0.1.0) (0.44.0)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.13/dist-packages (from polars->ultralytics==8.3.204->mediasearch==0.1.0) (1.35.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics==8.3.204->mediasearch==0.1.0) (1.17.0)
Building wheels for collected packages: mediasearch
  Building wheel for mediasearch (pyproject.toml) ... done
  Created wheel for mediasearch: filename=mediasearch-0.1.0-py3-none-any.whl size=22898 sha256=74b47619039f14a79f5cb197e24d50d61e700d5ce999dc54c1adef6a60d7fab0
  Stored in directory: /tmp/pip-ephem-wheel-cache-zuc8keai/wheels/81/d1/f6/4737326833ce371c474f6d50fbc2667a291b74852afd2ea5b0
Successfully built mediasearch
Installing collected packages: mediasearch
Successfully installed mediasearch-0.1.0

In [ ]:
!python3 run.py

 * Serving Flask app 'app'
 * Debug mode: off
2026-09-05 16:38:12,338 - werkzeug - INFO - WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.28.0.12:5000
2026-09-05 16:38:12,338 - werkzeug - INFO - Press CTRL+C to quit
2026-09-05 16:38:15,252 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:15] "GET / HTTP/1.1" 200 -
2026-09-05 16:38:15,738 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:15] "GET /static/style.css HTTP/1.1" 304 -
2026-09-05 16:38:15,741 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:15] "GET /static/app.js HTTP/1.1" 304 -
2026-09-05 16:38:16,260 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:16] "GET /api/images?page=1&page_size=30 HTTP/1.1" 200 -
2026-09-05 16:38:16,284 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:16] "GET /api/videos?page=1&page_size=24 HTTP/1.1" 200 -
2026-09-05 16:38:28,670 - root - INFO - Tokenizing the query...
2026-09-05 16:38:30,633 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:30] "POST /api/videos/search HTTP/1.1" 200 -
/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4
2026-09-05 16:38:31,159 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7378.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video9823.mp4
2026-09-05 16:38:31,164 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7378.mp4 HTTP/1.1" 206 -
2026-09-05 16:38:31,165 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9823.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8979.mp4
2026-09-05 16:38:31,182 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8979.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9681.mp4
2026-09-05 16:38:31,184 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9681.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8661.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video8895.mp4
2026-09-05 16:38:31,314 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8895.mp4 HTTP/1.1" 206 -
2026-09-05 16:38:31,316 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8661.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4
2026-09-05 16:38:31,331 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7500.mp4
2026-09-05 16:38:32,226 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:32] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7500.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8601.mp4
2026-09-05 16:38:32,634 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:32] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8601.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4
2026-09-05 16:38:33,198 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:33] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9823.mp4
2026-09-05 16:38:33,216 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:33] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9823.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7378.mp4
2026-09-05 16:38:33,270 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:33] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7378.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8895.mp4
2026-09-05 16:38:33,458 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:33] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8895.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8661.mp4
2026-09-05 16:38:34,145 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:34] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8661.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4
2026-09-05 16:38:37,522 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:37] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8979.mp4
2026-09-05 16:38:38,077 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:38] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8979.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7500.mp4
2026-09-05 16:38:38,649 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:38] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7500.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8895.mp4
2026-09-05 16:38:38,672 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:38] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8895.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4
2026-09-05 16:38:38,816 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:38] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9823.mp4
2026-09-05 16:38:40,001 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9823.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7378.mp4
2026-09-05 16:38:40,152 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7378.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8895.mp4
2026-09-05 16:38:40,306 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8895.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8661.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4
2026-09-05 16:38:40,310 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8661.mp4 HTTP/1.1" 206 -
2026-09-05 16:38:40,311 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7500.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video8979.mp4
2026-09-05 16:38:40,453 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7500.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4
2026-09-05 16:38:40,453 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8979.mp4 HTTP/1.1" 206 -
2026-09-05 16:38:40,455 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7378.mp4
2026-09-05 16:38:40,607 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7378.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8661.mp4
2026-09-05 16:38:40,779 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:40] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8661.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4
2026-09-05 16:38:41,349 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:41] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8675.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7500.mp4
2026-09-05 16:38:46,772 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:46] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7500.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8979.mp4
2026-09-05 16:38:46,776 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:46] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8979.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4
2026-09-05 16:38:51,838 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:51] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8476.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9681.mp4
2026-09-05 16:38:53,196 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:38:53] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9681.mp4 HTTP/1.1" 206 -
2026-09-05 16:39:03,762 - root - INFO - Tokenizing the query...
2026-09-05 16:39:05,088 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:05] "POST /api/videos/search HTTP/1.1" 200 -
/content/MSR-VTT/MSRVTT_Videos/video/video9336.mp4
2026-09-05 16:39:27,395 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:27] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9336.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4
2026-09-05 16:39:27,397 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:27] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7236.mp4
2026-09-05 16:39:27,419 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:27] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7236.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9511.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video9535.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video7616.mp4
2026-09-05 16:39:27,425 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:27] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9511.mp4 HTTP/1.1" 206 -
2026-09-05 16:39:27,426 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:27] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7616.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9975.mp4
2026-09-05 16:39:27,428 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:27] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9535.mp4 HTTP/1.1" 206 -
2026-09-05 16:39:27,428 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:27] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9975.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8497.mp4
2026-09-05 16:39:27,571 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:27] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8497.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7209.mp4
2026-09-05 16:39:29,363 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:29] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7209.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9622.mp4
2026-09-05 16:39:31,325 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:31] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9622.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9325.mp4
2026-09-05 16:39:35,963 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:35] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9325.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8330.mp4
2026-09-05 16:39:35,964 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:35] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8330.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9691.mp4
2026-09-05 16:39:36,701 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:36] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9691.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9755.mp4
2026-09-05 16:39:42,164 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9755.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7844.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video7138.mp4
2026-09-05 16:39:42,377 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7844.mp4 HTTP/1.1" 206 -
2026-09-05 16:39:42,379 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7138.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8934.mp4
2026-09-05 16:39:42,386 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8934.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9806.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video9489.mp4
2026-09-05 16:39:42,401 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9806.mp4 HTTP/1.1" 206 -
2026-09-05 16:39:42,401 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9489.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7732.mp4
2026-09-05 16:39:42,429 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7732.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9451.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video7752.mp4
2026-09-05 16:39:42,748 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7752.mp4 HTTP/1.1" 206 -
2026-09-05 16:39:42,749 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9451.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7796.mp4
2026-09-05 16:39:42,751 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7796.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7795.mp4
2026-09-05 16:39:42,754 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:42] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7795.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4
2026-09-05 16:39:46,868 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:46] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7616.mp4
2026-09-05 16:39:47,369 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:47] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7616.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9622.mp4
2026-09-05 16:39:50,205 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:50] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9622.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8497.mp4
2026-09-05 16:39:52,370 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:52] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8497.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9975.mp4
2026-09-05 16:39:52,372 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:52] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9975.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9535.mp4
2026-09-05 16:39:52,374 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:52] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9535.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9755.mp4
2026-09-05 16:39:57,257 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:39:57] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9755.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7138.mp4
2026-09-05 16:40:06,881 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:06] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7138.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7844.mp4
2026-09-05 16:40:06,883 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:06] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7844.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9489.mp4
2026-09-05 16:40:06,968 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:06] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9489.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9622.mp4
2026-09-05 16:40:23,021 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:23] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9622.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9451.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video7795.mp4
2026-09-05 16:40:23,031 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:23] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7795.mp4 HTTP/1.1" 206 -
2026-09-05 16:40:23,032 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:23] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9451.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9806.mp4
2026-09-05 16:40:23,046 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:23] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9806.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video7796.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video7732.mp4
2026-09-05 16:40:23,050 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:23] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4 HTTP/1.1" 206 -
2026-09-05 16:40:23,051 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:23] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7796.mp4 HTTP/1.1" 206 -
2026-09-05 16:40:23,052 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:23] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7732.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7616.mp4
2026-09-05 16:40:23,055 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:23] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video7616.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9755.mp4
2026-09-05 16:40:38,323 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:38] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9755.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9535.mp4
2026-09-05 16:40:43,277 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:43] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9535.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9975.mp4
2026-09-05 16:40:43,278 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:43] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9975.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video8497.mp4
2026-09-05 16:40:43,301 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:43] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8497.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9535.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video8497.mp4
2026-09-05 16:40:48,414 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:48] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video9535.mp4 HTTP/1.1" 206 -
2026-09-05 16:40:48,415 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:48] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8497.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video9975.mp4
/content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4
2026-09-05 16:40:48,438 - werkzeug - INFO - 127.0.0.1 - - [05/Sep/2026 16:40:48] "GET /api/media?path=/content/MSR-VTT/MSRVTT_Videos/video/video8089.mp4 HTTP/1.1" 206 -
/content/MSR-VTT/MSRVTT_Videos/video/video7616.mp4